#!/bin/bash

# Quick Fix: Install SDKs Despite Compilation Errors
# This script temporarily stubs out Facebook code, installs SDKs, then restores

set -e

PROJECT_PATH="/Users/pedromartinez/Dev/bdb/ineuj"
FACEBOOK_CS="$PROJECT_PATH/Assets/Commons/Runtime/Services/AppFacebook.cs"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status() { echo -e "${BLUE}[INFO] $1${NC}"; }
print_success() { echo -e "${GREEN}[SUCCESS] $1${NC}"; }
print_warning() { echo -e "${YELLOW}[WARNING] $1${NC}"; }
print_error() { echo -e "${RED}[ERROR] $1${NC}"; }

echo "=========================================="
echo "  Quick Fix: SDK Installation            "
echo "=========================================="
echo

# Step 1: Kill Unity if running
print_status "Step 1/5: Stopping Unity processes..."
ps aux | grep -E "Unity" | grep -v grep | awk '{print $2}' | xargs kill -9 2>/dev/null || true
sleep 2
print_success "✓ Unity stopped"

# Step 2: Backup Facebook code
print_status "Step 2/5: Backing up AppFacebook.cs..."
if [[ -f "$FACEBOOK_CS" ]]; then
    cp "$FACEBOOK_CS" "${FACEBOOK_CS}.backup_$(date +%Y%m%d_%H%M%S)"
    print_success "✓ Backup created"
else
    print_warning "AppFacebook.cs not found, skipping backup"
fi

# Step 3: Create temporary stub
print_status "Step 3/5: Creating temporary stub for AppFacebook.cs..."
cat > "$FACEBOOK_CS" << 'EOFSTUB'
// TEMPORARY STUB - Restore from backup after SDK installation
// This file is auto-generated by quickFixAndInstall.sh

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Cysharp.Threading.Tasks;

namespace Boardible.Commons
{
    public class AppFacebook
    {
        private static AppFacebook instance;
        public static AppFacebook Instance => instance ?? (instance = new AppFacebook());
        
        public bool IsLoggedIn => false;
        public string AccessToken => null;
        
        public async Task<bool> Login()
        {
            await Task.Delay(100);
            return false;
        }
        
        public void Logout() { }
        public void Initialize() { }
    }
}
EOFSTUB

print_success "✓ Temporary stub created"

# Step 4: Run SDK installation
print_status "Step 4/5: Installing Firebase and Facebook SDKs..."
echo
cd "$PROJECT_PATH"
./Scripts/updatePackages.sh --all --clean

if [[ $? -eq 0 ]]; then
    print_success "✓ SDKs installed successfully"
else
    print_error "SDK installation failed"
    print_warning "Check logs for details"
    exit 1
fi

# Step 5: Instructions for restoration
echo
print_success "=========================================="
print_success "  Installation Complete!                  "
print_success "=========================================="
echo
print_warning "IMPORTANT: Restore your original AppFacebook.cs"
echo
echo "Find your backup file:"
ls -lht "${FACEBOOK_CS}.backup_"* 2>/dev/null | head -5
echo
echo "To restore:"
echo "  1. Find the most recent backup above"
echo "  2. Copy it back:"
echo "     cp ${FACEBOOK_CS}.backup_YYYYMMDD_HHMMSS ${FACEBOOK_CS}"
echo
echo "Or restore automatically (uses most recent backup):"
echo "  LATEST=\$(ls -t ${FACEBOOK_CS}.backup_* | head -1)"
echo "  cp \"\$LATEST\" ${FACEBOOK_CS}"
echo
print_status "After restoration:"
echo "  1. Open Unity project"
echo "  2. Wait for recompilation"
echo "  3. Check that Facebook SDK types are available"
echo "  4. Build your project"
echo
